[[redirects]]
  from = "/api/*"
  to = "https://vault.echs.top/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/identity/*"
  to = "https://vault.echs.top/identity/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/icons/*"
  to = "https://vault.echs.top/icons/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/notifications/*"
  to = "https://vault.echs.top/notifications/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/attachments/*"
  to = "https://vault.echs.top/attachments/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
